CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    telefone VARCHAR(11),
    endereco VARCHAR(255)
    );


CREATE TABLE IF NOT EXISTS tecnicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(160),
    telefone VARCHAR(20),
    especialidade VARCHAR(100),
    disponivel BOOLEAN DEFAULT TRUE
    );


CREATE TABLE IF NOT EXISTS servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(200) NOT NULL,
    tipo VARCHAR(100),
    custo DECIMAL(12,2),
    tempo_estimado_minutos INTEGER
    );


CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
    );


CREATE TABLE IF NOT EXISTS ordens_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cliente_id BIGINT NOT NULL,
    tecnico_id BIGINT NOT NULL,
    servico_id BIGINT NOT NULL,

    status VARCHAR(255),

    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_inicio TIMESTAMP,
    data_fim TIMESTAMP,

    observacoes VARCHAR(500),

    valor_total DECIMAL(12,2),

    CONSTRAINT fk_ordem_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES clientes(id),

    CONSTRAINT fk_ordem_tecnico
    FOREIGN KEY (tecnico_id)
    REFERENCES tecnicos(id),

    CONSTRAINT fk_ordem_servico
    FOREIGN KEY (servico_id)
    REFERENCES servicos(id)
    );