-- 1. Cria a tabela de empresas/tenants
CREATE TABLE tenants (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR(255) NOT NULL UNIQUE
);

-- 2. Cria um tenant inicial
INSERT INTO tenants (nome)
VALUES ('Empresa Principal');

-- 3. Adiciona tenant_id nas tabelas existentes
ALTER TABLE clientes
    ADD COLUMN tenant_id BIGINT;

ALTER TABLE tecnicos
    ADD COLUMN tenant_id BIGINT;

ALTER TABLE servicos
    ADD COLUMN tenant_id BIGINT;

ALTER TABLE usuarios
    ADD COLUMN tenant_id BIGINT;

-- 4. Associa os registros existentes ao tenant inicial
UPDATE clientes
SET tenant_id = (SELECT id FROM tenants WHERE nome = 'Empresa Principal');

UPDATE tecnicos
SET tenant_id = (SELECT id FROM tenants WHERE nome = 'Empresa Principal');

UPDATE servicos
SET tenant_id = (SELECT id FROM tenants WHERE nome = 'Empresa Principal');

UPDATE usuarios
SET tenant_id = (SELECT id FROM tenants WHERE nome = 'Empresa Principal');

-- 5. Agora que todos possuem tenant, torna obrigatório
ALTER TABLE clientes
    ALTER COLUMN tenant_id SET NOT NULL;

ALTER TABLE tecnicos
    ALTER COLUMN tenant_id SET NOT NULL;

ALTER TABLE servicos
    ALTER COLUMN tenant_id SET NOT NULL;

ALTER TABLE usuarios
    ALTER COLUMN tenant_id SET NOT NULL;

-- 6. Cria as chaves estrangeiras
ALTER TABLE clientes
    ADD CONSTRAINT fk_cliente_tenant
        FOREIGN KEY (tenant_id)
            REFERENCES tenants(id);

ALTER TABLE tecnicos
    ADD CONSTRAINT fk_tecnico_tenant
        FOREIGN KEY (tenant_id)
            REFERENCES tenants(id);

ALTER TABLE servicos
    ADD CONSTRAINT fk_servico_tenant
        FOREIGN KEY (tenant_id)
            REFERENCES tenants(id);

ALTER TABLE usuarios
    ADD CONSTRAINT fk_usuario_tenant
        FOREIGN KEY (tenant_id)
            REFERENCES tenants(id);